database:
  production:
    dsn: dbi:SQLite:dbname=data/production/expense_tracker.sqlite
    user:
    password:
  development:
    dsn: dbi:SQLite:dbname=data/production/expense_tracker.sqlite
    user:
    password:



# application menu 
app_menu:
  anonymous:
    000_home:
      text: Home
      value: /
    001_slide:
      text: Cluj.PM Slide Photo Gallery
      value: /clujpm_gallery/slide
    002_grid:
      text: Cluj.PM Grid Photo Gallery
      value: /clujpm_gallery/grid
    01_login:
      text: Log In
      value: /login
    02_signup:
      text: Sign Up
      value: /sign-up
    03_about:
      text: About
      value: /about

  regular:  
    000_home:
      text: Home
      value: /
    001_slide:
      text: Cluj.PM Slide Photo Gallery
      value: /clujpm_gallery/slide
    002_grid:
      text: Cluj.PM Grid Photo Gallery
      value: /clujpm_gallery/grid
    01_user_menu:
      text: User Menu
      value: /user/menu
    03_logout:
      text: Logout
      value: /logout  
    04_about:
      text: About
      value: /user/about

google_analytics_code: UA-407609-8
